name: PR Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - closed
      - reopened
      - synchronize

jobs:
  pr-title-check:
    name: Commitlint
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get dependencies
        run: npm install
      - name: Run commitlint
        uses: JulienKode/pull-request-name-linter-action@v0.1.2
      - name: Comment on failure
        if: failure()
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: The name of this pull request failed linting. Please fix it before merging.
      - name: Label on failure
        if: failure()
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: fix-title
          type: add
      - name: Comment on success
        if: contains(toJson(github), 'fix-title' ) && !failure()
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: The name of this pull request looks good now.
      - name: Comment on success
        if: contains(toJson(github), 'fix-title' ) && !failure()
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: fix-title
          type: remove

  pr-assignment:
    name: Assignment
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewer/owner
        uses: kentaro-m/auto-assign-action@v1.1.1
